// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjKb2SN-tCTBpPCwFwGUK1M7m48CWycrg',
    appId: '1:206746871148:web:fab12bad0be0efe01aff49',
    messagingSenderId: '206746871148',
    projectId: 'ecenter-2d8c4',
    authDomain: 'ecenter-2d8c4.firebaseapp.com',
    storageBucket: 'ecenter-2d8c4.firebasestorage.app',
    measurementId: 'G-8GT5J7HT6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjI4LX_SSktcHdSV1bcBGQon3D9rO-_g4',
    appId: '1:206746871148:android:8d87ccce165a5f9d1aff49',
    messagingSenderId: '206746871148',
    projectId: 'ecenter-2d8c4',
    storageBucket: 'ecenter-2d8c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzAGdkPy2z3gTDKo_t33vRvdLu0n3xPrc',
    appId: '1:206746871148:ios:970f00781c0033721aff49',
    messagingSenderId: '206746871148',
    projectId: 'ecenter-2d8c4',
    storageBucket: 'ecenter-2d8c4.firebasestorage.app',
    iosBundleId: 'com.example.tiktokVideo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzAGdkPy2z3gTDKo_t33vRvdLu0n3xPrc',
    appId: '1:206746871148:ios:970f00781c0033721aff49',
    messagingSenderId: '206746871148',
    projectId: 'ecenter-2d8c4',
    storageBucket: 'ecenter-2d8c4.firebasestorage.app',
    iosBundleId: 'com.example.tiktokVideo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjKb2SN-tCTBpPCwFwGUK1M7m48CWycrg',
    appId: '1:206746871148:web:9bb41a81cb845c751aff49',
    messagingSenderId: '206746871148',
    projectId: 'ecenter-2d8c4',
    authDomain: 'ecenter-2d8c4.firebaseapp.com',
    storageBucket: 'ecenter-2d8c4.firebasestorage.app',
    measurementId: 'G-M6FDEQFWTD',
  );
}
